### ISSUE TITLE
CSS复习

### ISSUE THREAD

**Issue by hanrenguang** [hanrenguang/notes#20]
复习 `CSS` 基础知识，查漏补缺，并做些笔记，很基础，大佬请略过。持续更新中...

## 样式与内容分离
在 `HTML` 中可以使用一些标签或标签的属性来表现一定的样式效果，然而这并不酷，容易造成一些混乱，如果项目有多个维护者，会增加不少维护成本。所以应尽量将内容和样式分离，内容用语义化标签包裹，且不参与样式的表现，样式细节等均交由 `CSS` 解决。这样才比较酷嘛！

## 选择器
- 标签选择器（tag）
- 类选择器（class）
- ID选择器（id）
- 伪类选择器
- 基于关系的选择器

## 使用伪类选择器和关系选择器实现二级标题
```HTML
<header>
    <nav>
      <ul>
        <li>
          <a href="#">水果</a>
          <ul>
            <li>
              <a href="#">椰子</a>
            </li>
            <li>
              <a href="#">葡萄</a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </header>
```
```CSS
ul, li {
  list-style: none;
}

header {
  width: 100%;
  height: 50px;
  border-bottom: 1px solid #ddd;
  box-shadow: 0 4px 3px #eee;
}
header nav {
  margin-left: 20px;
}
ul {
  width: 50px;
}
a {
  display: block;
  line-height: 50px;
  text-decoration: none;
}
nav ul ul {
  display: none;
}
nav ul li:hover > ul {
  display: block;
}
```

## 在文字前后插入图片
使用 `::before` 和 `::after` 伪元素和 `content` 属性实现
```CSS
p::before {
  content: url("/path/bf.png");
}
```

## 指定列表项标记的样式
`list-style` 属性在表现无序列表时，使用 `disc`, `circle` 和 `square`，有序列表使用 `decimal`, `lower-roman`, `upper-roman`, `lower-latin` 和 `upper-latin`。

## 计数器
通过 `counter-reset` 属性设置一个计数器，包括其名字和初始值，初始值默认为0。例如：
```CSS
div.parent {
  counter-reset: name initNum;
}
```
使计数器的值增加或减少，通过 `counter-increment` 属性实现，在需要递增或递减的子元素添加该属性即可。显示计数结果可使用 `counter` 或 `counters` 方法与 `content` 属性相结合。下面是个例子：
```HTML
<div class="parent">
  <p>我是1</p>
  <p>我是2</p>
  <p>我是3</p>
  <p>我是4</p>
  <p>我是5</p>
</div>
```
```CSS
div.counter {
  counter-reset: list;
}

div.counter p:before {
  content: counter(list) ". ";
  counter-increment: list 1; /* list 为需要递增或递减的计数器名字，后接的数值为每次的增量 */
}
```
计数器还有许多复杂用法，可以自行查阅资料。

## border-style
边框样式有以下几种：`none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset`

## text-align: justify | justify-all
当值为 `justify` 时，文字向两侧对齐，对最后一行无效。当值为 `justify-all` 时，文字向两侧对齐，最后一行也向两侧对齐，然鹅，好像 `justify-all` 没有被浏览器实现。

## text-indent
在浏览器中，能使用固定尺寸或宽度百分比实现文本缩进。

## 边框的颜色
如果没有给边框设置 `border-color` 属性，则边框的颜色将取元素内容的前景色（如字体颜色）。
