### ISSUE TITLE
图片固定宽高比

### ISSUE THREAD

**Issue by hanrenguang** [hanrenguang/notes#5]
## div固定宽高比
HTML结构：
```HTML
<div></div>
```
CSS样式：
```CSS
div {
  height: 0;
  padding-top: 50%;
  background-color: #000;
}
```
可以观察到页面上出现了一个宽高比为2：1的div，要改变比例只需要改变其padding-top的百分比。

## 图片固定宽高比
很简单，只需要把图片设置为div的背景图片，并使其铺满div即可：
```CSS
div {
  height: 0;
  padding-top: 50%;
  background: url(xxx.jpg) no-repeat 0 0;
  background-size: 100% 100%;
}
```
